<?php

namespace BasketballBundle\Repository;

use BasketballBundle\Entity\GameResult;

/**
 * GameResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameResultRepository extends \Doctrine\ORM\EntityRepository
{
    public function getReadyGameResult($score, $firstTeam, $secondTeam, $gameDate)
    {
        $result = new GameResult();
        $result->setScore($score);
        $result->setTeam1($firstTeam);
        $result->setTeam2($secondTeam);
        $result->setDate($gameDate);
        
        return $result;
    }
}
