<?php

namespace BasketballBundle\Repository;

/**
 * GameResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameResultRepository extends \Doctrine\ORM\EntityRepository
{
}
