<?php

namespace BasketballBundle\Repository;

/**
 * GameListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameListRepository extends \Doctrine\ORM\EntityRepository
{
}
