<?php

namespace BasketballBundle\Repository;

/**
 * NextGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NextGameRepository extends \Doctrine\ORM\EntityRepository
{
}
