<?php

namespace BasketballBundle\Repository;

/**
 * PlayersTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayersTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
