<?php

namespace BasketballBundle\Repository;

/**
 * PlayerListControllerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerListControllerRepository extends \Doctrine\ORM\EntityRepository
{
}
