<?php

namespace BasketballBundle\Repository;

/**
 * PlayersListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayersListRepository extends \Doctrine\ORM\EntityRepository
{
}
