<?php

namespace BasketballBundle\Repository;

/**
 * SpecialisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialisationRepository extends \Doctrine\ORM\EntityRepository
{
}
